### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by GamingMas73r** [Externalizable/bongo.cat#18]
Chrome just outputs in console Lowlag is undefined, when a key is pressed it doesn't play a sound but it'll still switch musical objects

**Comment by BadCoder2** [comment]
I'm getting this error too.
Running ChromeOS
Chrome version 71.0.3578.127
I host this on a server so the sound will work
Server output:
`127.0.0.1 - - [06/Feb/2019 10:24:36] "GET /images/bongo.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:36] "GET /images/keyboard.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:36] "GET /style/style.css HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:36] "GET /js/sm2/js/soundmanager2-jsmin.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:36] "GET /js/core.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:37] "GET /images/cymbal.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:37] "GET /images/marimba.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:37] "GET /images/m1.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:37] "GET /images/m2.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:37] "GET /images/l1.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:37] "GET /images/l2.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:37] "GET /images/r1.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Feb/2019 10:24:37] "GET /images/r2.png HTTP/1.1" 200 -`
Console:
`lowLag.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
soundmanager2-jsmin.js:32 SoundManager: No Flash detected. Trying HTML5-only mode.
soundmanager2-jsmin.js:32 -- SoundManager 2: HTML5 support tests (/^(probably|maybe)$/i): mp3: true, mp4: true, ogg: true, wav: true --
soundmanager2-jsmin.js:32 -- SoundManager 2 V2.97a.20120624 (HTML5-only mode) --
soundmanager2-jsmin.js:32 soundManager::init()
soundmanager2-jsmin.js:32 -- SoundManager 2: loaded --
jquery.min.js:2 jQuery.Deferred exception: lowLag is not defined ReferenceError: lowLag is not defined
    at HTMLDocument.<anonymous> (http://0.0.0.0:8000/js/core.js:69:5)
    at l (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:29375)
    at c (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery.min.js:2
content.js:1 Feedback rendered
antiphishing.js:1 Sending APH request...
jquery.min.js:2 Uncaught ReferenceError: lowLag is not defined
    at HTMLDocument.<anonymous> (core.js:69)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
(9) core.js:132 Uncaught ReferenceError: lowLag is not defined
    at Function.$.sound (core.js:132)
    at Function.$.play (core.js:121)
    at HTMLDocument.<anonymous> (core.js:203)
    at HTMLDocument.dispatch (jquery.min.js:2)
    at HTMLDocument.y.handle (jquery.min.js:2)`
Thanks in advance.

**Comment by mmccall0813** [comment]
i also have this issue on chromebook

**Comment by lowercasebtw** [comment]
crazy
